pool: v-aprozo
  
steps:
    
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate 2'
  inputs:
    certSecureFile: 'cert2.p12'
    certPwd: '$(cert2_pwd)'
    keychain: 'temp'
