pool: v-aprozo

jobs:
  - job: 'Apps'
          
    steps:

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'cert1.p12'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'echo $(reference.secureFilePath)'