pool:
  vmImage: 'macos-latest'
  
steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'cert1.p12'
    certPwd: '$(cert_pwd)'
    keychain: 'temp'
    
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'cert2.p12'
    certPwd: '$(cert_pwd)'
    keychain: 'temp'
