pool: 
  vmImage: 'macos-latest'
  
steps:
    
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'cert1.p12'
    certPwd: '$(password1)'
    keychain: 'temp'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'cert2.p12'
    certPwd: '$(password2)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'abttxamarintestapp.mobileprovision'
    removeProfile: false
- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: false