pool:
  vmImage: 'macos-latest'

jobs:
  - job: 'Apps'
          
    steps:

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'cert1.p12'
        certPwd: '$(password1)'
        keychain: 'temp'
        keychainPassword: '$(keychain_password)'

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'cert2.p12'
        certPwd: '$(password2)'
        keychain: 'temp'
        keychainPassword: '$(keychain_password)'