pool: v-aprozo

jobs:
  - job: 'Apps'
          
    steps:

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'cert1.p12'
    
    - task: CmdLine@2
      inputs:
        script: 'echo $(secureFilePath)'