pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'Certificates-Dev.p12'
    certPwd: '$(P12password)'

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: '$(P12password)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: 'abttxamarintestapp.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    signingOption: 'manual'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    scheme: ''
    args: '-UseModernBuildSystem=NO'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: AppCenterTest@1
  displayName: 'Test with Visual Studio App Center'
  inputs:
    appFile: '**/*.ipa'
  enabled: false
  condition: succeededOrFailed()

- task: AppCenterDistribute@2
  displayName: 'Deploy **/*.ipa to Visual Studio App Center'
  inputs:
    appFile: '**/*.ipa'
    symbolsIncludeParentDirectory: false
  enabled: false
  condition: succeededOrFailed()

