pool:
  name: v-aprozo
  demands: xcode

steps:
- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'aa0eee1d-b19f-4b15-bcd5-197f0592efb5'
    certPwd: '$(P12password)'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: '0303da7e-954f-4d35-b578-e4c39669cd8a'

- task: Xcode@5
  displayName: 'Xcode test'
  inputs:
    actions: test
    configuration: '$(TestConfiguration)'
    sdk: '$(TestSDK)'
    xcWorkspacePath: '$(Parameters.xcWorkspacePath)'
    scheme: '$(Parameters.scheme)'
    xcodeVersion: '$(Parameters.xcodeVersion)'
    signingOption: default
    destinationPlatformOption: iOS
    publishJUnitResults: true
  enabled: false

- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    xcWorkspacePath: '$(Parameters.xcWorkspacePath)'
    scheme: '$(Parameters.scheme)'
    xcodeVersion: '$(Parameters.xcodeVersion)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: AppCenterTest@1
  displayName: 'Test with Visual Studio App Center'
  inputs:
    appFile: '**/*.ipa'
  enabled: false
  condition: succeededOrFailed()

- task: AppCenterDistribute@2
  displayName: 'Deploy **/*.ipa to Visual Studio App Center'
  inputs:
    appFile: '**/*.ipa'
    symbolsIncludeParentDirectory: false
  enabled: false
  condition: succeededOrFailed()

